### ISSUE TITLE
Merge to ks-mode?

### ISSUE THREAD

**Issue by ghost** [LeonardMH/kos-scripts#5]
Hi @LeonardMH!

It's a treat to see someone getting some value out of ks-mode. Will ksx-mode be backward compatible for people writing plain Kerboscript? If so, would you consider becoming a committer/maintainer of ks-mode?

Alternatively, I could place a deprecation notice on ks-mode, since (as you can see) I haven't worked on it for a long time, and it sounds like you currently have the fire to make the best Kerboscript mode ever! :heart:

**Comment by LeonardMH** [comment]
Hey there, thanks for giving me a great starting point (with tests even!). I'm relatively new to the emacs-lisp world and I learned quite a bit from the ks-mode implementation. It was a relief to find anything at all TBH as the union of emacs hackers and kOS users has to be a pretty small group.

> Will ksx-mode be backward compatible for people writing plain Kerboscript?

Yes, I do plan to maintain backwards compatibility. I have no plans to add any "ksx" features that aren't prefixed by "@ksx", which makes things easy from a transpiler standpoint as well as from a major mode standpoint (invoke ksx specific font locking only after seeing @ksx, once I figure out how to do that).

> If so, would you consider becoming a committer/maintainer of ks-mode?
>
> Alternatively, I could place a deprecation notice on ks-mode, since (as you can see) I haven't worked on it for a long time, and it sounds like you currently have the fire to make the best Kerboscript mode ever!

At the moment I'm just hacking around, learning about emacs-lisp and language parsing while having a little fun, and most likely breaking things. So I'd rather not 'support' anything right now (not that anyone is knocking my door down) but if I reach a point where some semblance of stability exists I'll split both ksx-mode and the ksx transpiler/minifier out into their own repositories and ping you so ks-mode can be deprecated.

In the meantime I think adding a note to the ks-mode readme pointing people here would not be a bad idea as there have been a couple of improvements not related to my ksx-lang extensions:

1. Deriving from prog-mode rather than fundamental (filed an issue on ks-mode for this one line change) gives you a couple of features for free and auto-enables some of your third party packages which use the prog-mode-hook to add features.
2. Added proper comment wrapping for use with `fill-region` which was surprisingly difficult for some reason, I eventually just copied all of the 'fill' related code from rust-mode and things started to work.
3. Added several suffixes which were not defined, will continue to add to this, and would also like to make them semantically accurate but that requires some pretty intelligent parsing so maybe not something I'll have time to do.

**Comment by LeonardMH** [comment]
Oh getting proper highlighting for floating point numbers also turned out to be surprisingly difficult and something that I spent way too much time on. 

That turned out to just be a problem if you're using `highlight-numbers` mode (which spacemacs does by default), the default regex for that mode does not consider floating point numbers as a single entity and instead something like `324.48` would be highlighted as two separate numbers with the '.' not being font-locked. That was driving me crazy so I fixed it by adding:

```emacs-lisp
  ; highlight-numbers generic number regex does not account for floating point
  ; numbers, and it overrides the regex that I defined above to highlight these
  ; numbers, so I need to tell it that kOS supports these numbers...
  (if (featurep 'highlight-numbers)
      (puthash
       'ksx-mode
       (rx (and symbol-start (or (and (+ digit) (? (and "." (* digit))))) symbol-end))
       highlight-numbers-modelist)))
```

inside the `define-derive-mode` form.

**Comment by ghost** [comment]
> I'm relatively new to the emacs-lisp world and I learned quite a bit from the ks-mode implementation.

That's a great compliment, thanks! `ks-mode` was the first LISP I had written, excluding my `.emacs` file. I could never have got it working without the test suite. :)

>  I'd rather not 'support' anything right now

Of course! That did sound kind of "heavy", didn't it? No worries at all.

> if I reach a point where some semblance of stability exists I'll split both ksx-mode and the ksx transpiler/minifier out into their own repositories and ping you so ks-mode can be deprecated.

Excellent. I just want anybody who goes looking to get the "the best", and I think what you are working on will soon be that. I'll probably play KSP myself again, someday, and I look forward to trying out your stuff!
